name: Django CI/CD with Docker

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t main .

      - name: Run tests
        run: docker run --rm main sh -c "python manage.py test --settings=conf.settings"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 45.80.149.202
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/test_CDCI
            git pull origin master
            docker-compose down
            docker-compose up -d --build
